surfnet_suaas_self_service:
    resource: "@SURFnetSuAASSelfServiceBundle/Resources/config/routing.yml"
    prefix:   /self-service

surfnet_suaas_ra:
    resource: "@SURFnetSuAASRABundle/Resources/config/routing.yml"
    prefix:   /management

