surfnet_suaas_self_service:
    resource: "@SURFnetSuAASSelfServiceBundle/Controller/"
    type: annotation
    prefix:   /

surfnet_suaas_ra:
    resource: "@SURFnetSuAASRABundle/Controller/"
    type: annotation
    prefix:   /

surfnet_onelogin_saml:
    resource: "@SURFnetOneLoginBridgeBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
