surfnet_suaas_self_service:
    resource: "@SURFnetSuAASSelfServiceBundle/Controller/"
    type: annotation
    prefix:   /

surfnet_suaas_ra:
    resource: "@SURFnetSuAASRABundle/Resources/config/routing.yml"
    prefix:   /management

surfnet_onelogin_saml:
    resource: "@SURFnetOneLoginBridgeBundle/Controller/"
    type:     annotation
    prefix:   /
