security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        suaas:
            id: suaas.service.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        exceptions:
            pattern: ^/(login|start|saml/(redirect|metadata))
            anonymous: ~

        self_registration:
            pattern:  ^/
            saml: true
            provider: suaas
            form_login:
                login_path: /start
                use_referer: true
            logout:
                path:   /logout
                target: /start

    access_control:
        - { path: ^/(login|start), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/(redirect|metadata), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/management/ra, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/management, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
