security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        suaas:
            id: suaas.service.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        self_registration:
            pattern:  ^/(self\-service|saml)
            saml: true
            anonymous: ~

    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#        - { path: ^/saml, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/self-service/start, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/self-service, roles: ROLE_USER }
#        - { path: ^/management, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
