<?php

namespace SURFnet\SuAAS\DomainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Daan van Renterghem <dvrenterghem@ibuildings.nl>
 */
class OrganisationRepository extends EntityRepository
{
}
