parameters:
#    sur_fnet_one_login_bridge.example.class: SURFnet\OneLoginBridgeBundle\Example

services:
#    sur_fnet_one_login_bridge.example:
#        class: %sur_fnet_one_login_bridge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
