parameters:
    surfnet.onelogin_bridge.configuration.class:    SURFnet\OneLoginBridgeBundle\SAML\Configuration
    surfnet.onelogin_bridge.settings.class:         SURFnet\OneLoginBridgeBundle\SAML\Settings
    surfnet.saml.request.class:                     OneLogin_Saml_AuthRequest
    surfnet.saml.metadata.class:                    OneLogin_Saml_Metadata
    surfnet.saml.response.class:                    SURFnet\OneLoginBridgeBundle\Service\ResponseAdapter

services:
    surfnet.onelogin_bridge.configuration:
        public: false
        class: %surfnet.onelogin_bridge.configuration.class%
        arguments:
            - @router
            - %surfnet.onelogin_bridge.saml.target_url%
            - %surfnet.onelogin_bridge.saml.consumer_url%
            - %surfnet.onelogin_bridge.saml.issuer_name%
            - %surfnet.onelogin_bridge.saml.name_identifier_format%
            - %surfnet.onelogin_bridge.saml.certificate%

    surfnet.onelogin_bridge.settings:
        public: false
        class: %surfnet.onelogin_bridge.settings.class%
        arguments: [@surfnet.onelogin_bridge.configuration]

    surfnet.saml.request:
        class: %surfnet.saml.request.class%
        arguments: [@surfnet.onelogin_bridge.settings]

    surfnet.saml.metadata:
        class: %surfnet.saml.metadata.class%
        arguments: [@surfnet.onelogin_bridge.settings]

    surfnet.saml.response:
        class: %surfnet.saml.response.class%
        arguments: [@surfnet.onelogin_bridge.settings]

