parameters:
    suaas.twig.wizard_header_extension.class:           SURFnet\SuAAS\SelfServiceBundle\Twig\WizardHeaderExtension

services:
    suaas.twig.wizard_header_extension:
        class: %suaas.twig.wizard_header_extension.class%
        tags:
            - { name: twig.extension }
